create table if not exists public.chat_messages (id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,sender_name text not null check (char_length(sender_name) between 1 and 100),body text not null check (char_length(body) between 1 and 1000),created_at timestamptz not null default now());
alter table public.chat_messages enable row level security;
create policy "authenticated users read chat" on public.chat_messages for select to authenticated using (true);
create policy "users send own messages" on public.chat_messages for insert to authenticated with check (auth.uid() = user_id);
grant select, insert on public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;
alter publication supabase_realtime add table public.chat_messages;

